### ISSUE TITLE
Face detection with Opencv

### ISSUE THREAD

**Issue by KjetilIN** [RIT-NTNU-Bachelor/face-detection-opencv-cpp#2]
IDE: Switched from Visual Studio Code to Visual Studio.

**Comment by marhjoh** [comment]
### Readings

**CMake**

- [What is a CMake Generator](https://stackoverflow.com/questions/25941536/what-is-a-cmake-generator)
- [Understanding the purpose behind CMake](https://stackoverflow.com/questions/25751406/understanding-the-purpose-behind-cmake)
- [Configure and build with CMake Presets in Visual Studio Code](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-presets.md)
- [OpenCV C++ and Microsoft Visual Studio: A Complete Tutorial on Installation and Usage for Beginners](https://www.youtube.com/watch?v=trXs2r6xSnI)
- [How to install and use "make" in Windows?](https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows)
- [How to specify a compiler in CMake?](https://stackoverflow.com/questions/45933732/how-to-specify-a-compiler-in-cmake)

**Other**
- [Configure VS Code for Microsoft C++](https://code.visualstudio.com/docs/cpp/config-msvc#_run-vs-code-outside-the-developer-command-prompthttps://code.visualstudio.com/docs/cpp/config-msvc#_run-vs-code-outside-the-developer-command-prompt)
- [The Ninja build system](https://ninja-build.org/manual.html)

**Comment by marhjoh** [comment]
https://stackoverflow.com/questions/42679720/c-cannot-open-source-file
https://docs.opencv.org/4.x/d3/d52/tutorial_windows_install.html
https://stackoverflow.com/questions/31675150/cmake-command-is-not-recognized
https://cmake.org/download/
https://superuser.com/questions/1709437/how-can-i-update-the-kernel-in-wsl2-kernel-to-latest-release

**Comment by KjetilIN** [comment]
We know have multiple Demos with OpenCV
