### ISSUE TITLE
REFACTOR: optimize face detection

### ISSUE THREAD

**Issue by marhjoh** [RIT-NTNU-Bachelor/face-detection-opencv-cpp#4]
Make the face detection more accurate, will test different libraries within opencv

**Comment by marhjoh** [comment]
Face tracking is quite accurate per commit _614b835_. However, the eye tracking isn't working optimal on long range. Further work will be done to improve this. Switching cascade for the eyes helped.

**Comment by KjetilIN** [comment]
Close for now
