### ISSUE TITLE
Display videos utilizing DNN-model in C++

### ISSUE THREAD

**Issue by marhjoh** [RIT-NTNU-Bachelor/face-detection-opencv-cpp#5]
The bug is most definitly related to paths

![image](https://github.com/RIT-NTNU-Bachelor/face-detection-opencv-cpp/assets/94908112/a909e3e8-c437-45bb-9686-705aa839fb3a)

**Comment by marhjoh** [comment]
Managed to solve this in Python. However, will not work on this in C++.

**Comment by KjetilIN** [comment]
Closed due to C++ issues (Moved away from)
