### ISSUE TITLE
Running dlib in C++

### ISSUE THREAD

**Issue by marhjoh** [RIT-NTNU-Bachelor/face-detection-opencv-cpp#6]
Have difficulties running dlib in the same project as haar and dnn

**Comment by marhjoh** [comment]
Made able to run with Python, not C++

**Comment by marhjoh** [comment]
Made it able to run in C++, however only for local files - runs pretty slow. Check [issue about testing](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/issues/14).

**Comment by marhjoh** [comment]
# Update 03/29/2024 4 PM

I have the assets I utilized to make it work for me on my laptop @KjetilIN (and issued I encountered while I tried to make it work). The code for C++ utilize boost also, so this must also be downloaded.

## Videos
- [Install dLib and Create Lib C++ project Visual Studio Project](https://www.youtube.com/watch?v=BKGkA_K1KPA&list=WL&index=3&t=148s)
- [Installing DLIB library in Windows 10](https://www.youtube.com/watch?v=pHrgi8QLcKk&t=185s) **Not relevant for you on Linux**
- [Creating C++ project with using Dlib to track objects](https://www.youtube.com/watch?v=mlD3HIF5rGo)

## Forums
- [Unknown Error after building dlib for c++ properly, while importing it](https://stackoverflow.com/questions/69136319/unknown-error-after-building-dlib-for-c-properly-while-importing-it)
- [dlib installation on Windows 10](https://stackoverflow.com/questions/41912372/dlib-installation-on-windows-10) **Not relevant for you on Linux**
- [no module named distutils....but distutils installed?](https://stackoverflow.com/questions/69919970/no-module-named-distutils-but-distutils-installed)
- [How do files get into the External Dependencies in Visual Studio C++?](https://stackoverflow.com/questions/6769760/how-do-files-get-into-the-external-dependencies-in-visual-studio-c)
- [Penalty of the MSVS compiler flag /bigobj](https://stackoverflow.com/questions/15110580/penalty-of-the-msvs-compiler-flag-bigobj) **Made it work running from local save - not optimal at all**
- [Tutorial: Install and use packages with MSBuild in Visual Studio](https://learn.microsoft.com/nb-no/vcpkg/get_started/get-started-msbuild?pivots=shell-bash)

**Comment by marhjoh** [comment]
# Update 03/29/2024 4:30 PM

Linux dlib download video [press here](https://www.youtube.com/watch?v=z3G1c_XL0Ng)

**Comment by KjetilIN** [comment]
Code leads to core dump, meaning that is uses to much memory: 


![Image](https://github.com/RIT-NTNU-Bachelor/face-detection-opencv-cpp/assets/66110094/4fb1b656-574e-4a7c-a782-bb0291bf1a61)

**Comment by marhjoh** [comment]
@KjetilIN you can run it with [Penalty of the MSVS compiler flag /bigobj](https://stackoverflow.com/questions/15110580/penalty-of-the-msvs-compiler-flag-bigobj), but again it will run slow. I believe the issue relies in how dlib is retrieved. 

I will add the label "wont fix".
